name: Trimana Engine - Platform Linux build [Debug]

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Debug

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            submodules: 'true'

        - name: Configure CMake
          run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

        - name: Building
          run: cmake --build ${{github.workspace}}/build --config ${{ env.BUILD_TYPE }}
        

